apiVersion: v1
kind: Namespace
metadata:
  name:  test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: test
  labels:
    app: redisApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redisApp
  template:
    metadata:
      namespace: test
      labels:
        app: redisApp
      annotations:
        name: Fatih MANDIRALI
        job: FULL-STACK DEVELOPER        
    spec:
      containers:
        - name: redis-server
          image: redis:6.2-alpine
          ports:
          - containerPort: 80   

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: pgadminApp
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: test
  labels:
    app: pgadminApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadminApp
  template:
    metadata:
      namespace: test
      labels: 
        app: pgadminApp
    spec:
      containers:
        - name:  pgadmin-server
          image:  dpage/pgadmin4
          env:
          - name:  PGADMIN_DEFAULT_EMAIL
            value:  hairdresser@pgadmin.com 
          - name:  PGADMIN_DEFAULT_PASSWORD
            value:  hairdresser@123
          - name:  PGADMIN_LISTEN_PORT
            value:  "5050"
          ports:
          - containerPort: 5050    
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: postgreSqlApp
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
  namespace: test
  labels:
    app: postgreSqlApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgreSqlApp
  template:
    metadata:
      namespace: test
      labels: 
        app: postgreSqlApp
    spec:
      containers:
        - name:  postgres-server
          image:  postgres
          env:
          - name:  POSTGRESQL_PASSWORD
            value:  postgres 
          - name:  POSTGRES_HOST_AUTH_METHOD
            value:  trust
          - name:  TZ
            value:  Turkey
          ports:
          - containerPort: 5432
            protocol: TCP
  