apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: test
  labels:
    app: postgres
type: Opaque
data:
    postgres-root-username: cm9vdC1mbQ==
    postgres-root-password: cm9vdC1mbS1wYXNzd29yZA==